server:
  port: 8081
  context-path: /boot
  ##keytool -genkey -alias tomcat  -storetype PKCS12 -keyalg RSA -keysize 2048  -keystore keystore.p12 -validity 3650
  #ssl:
    #key-store: keystore.p12
    #key-store-password: 940610
    #key-store-type: PKCS12
    #key-alias: tomcat
logging:
  file: D:/pLog/boot/log.log
  level: debug
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .th
  datasource:
          name: test
          url: jdbc:mysql://rm-wz9ewi67416v36qqgjo.mysql.rds.aliyuncs.com:3306/htest
          username: root
          password: Mjw940610
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.mjw.bean
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mjw:
  name: haha
  age: 12